#This is a makefile

linux:
	gcc -Iinclude/ src/main.c src/timer.c src/model.c src/vertex.c src/texture_vertex.c src/normal_vertex.c src/triangle.c src/quad.c src/texture.c src/texture_box.c src/bounding_box.c src/draw.c src/write_to.c -lSOIL -lobj -lGL -lGLU -lglut -lm -o func
